export const UI = {
  FORMATS: document.querySelectorAll('.format'),
  QUANTITY: document.querySelector('.quantity'),
  MINUS_BTN: document.querySelector('.minus'),
  PLUS_BTN: document.querySelector('.plus'),
  SEND_BTN: document.querySelector('.send'),
  UPLOAD_BTN: document.querySelector('.upload'),
  HIDDEN_UPLOAD: document.querySelector('.hidden-upload'),
  SIDE_CONTROLS_BTNS: document.querySelectorAll('.side-controls-shifter svg'),
  SIDE_CONTROL_PAGE_1: document.querySelector('.side-control-page-1'),
  SIDE_CONTROL_PAGE_2: document.querySelector('.side-control-page-2'),
  ACTION_BUTTON: document.querySelectorAll('.action-button button'),
  IMAGE_WORKSPACE_SAPN: document.querySelector('.image-workspace span'),
  PREVIEW_CONTAINER_SPAN: document.querySelector('.preview-container span'),
  ROTATE: document.querySelectorAll('.side-control-page-1 .rotate svg'),
  FLIP: document.querySelectorAll('.side-control-page-1 .flip svg'),
  MOVE: document.querySelectorAll('.side-control-page-1 .move svg'),
  ASPECT_RATIO: document.querySelectorAll('.side-control-page-2 .aspect li'),
};